<?xml version="1.0" encoding="utf-8"?><Database Name="THUVIEN" Class="QuanLyThuVienDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BICHAN\SQLEXPRESS;Initial Catalog=THUVIEN;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="THUVIENConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietMuon" Member="ChiTietMuons">
    <Type Name="ChiTietMuon">
      <Column Name="maChiTietMuon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maPhieuMuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maTaiLieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChiTietMuon_ChiTietTinhTrangKhiTra" Member="ChiTietTinhTrangKhiTras" ThisKey="maChiTietMuon" OtherKey="maChiTietMuon" Type="ChiTietTinhTrangKhiTra" />
      <Association Name="PhieuMuon_ChiTietMuon" Member="PhieuMuon" ThisKey="maPhieuMuon" OtherKey="maPhieuMuon" Type="PhieuMuon" IsForeignKey="true" />
      <Association Name="TaiLieu_ChiTietMuon" Member="TaiLieu" ThisKey="maTaiLieu" OtherKey="maTaiLieu" Type="TaiLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietTinhTrangKhiTra" Member="ChiTietTinhTrangKhiTras">
    <Type Name="ChiTietTinhTrangKhiTra">
      <Column Name="maPhieuTra" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maChiTietMuon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLoaiTinhTrang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ChiTietMuon_ChiTietTinhTrangKhiTra" Member="ChiTietMuon" ThisKey="maChiTietMuon" OtherKey="maChiTietMuon" Type="ChiTietMuon" IsForeignKey="true" />
      <Association Name="LoaiTinhTrangKhiTra_ChiTietTinhTrangKhiTra" Member="LoaiTinhTrangKhiTra" ThisKey="maLoaiTinhTrang" OtherKey="maLoaiTinhTrang" Type="LoaiTinhTrangKhiTra" IsForeignKey="true" />
      <Association Name="PhieuTra_ChiTietTinhTrangKhiTra" Member="PhieuTra" ThisKey="maPhieuTra" OtherKey="maPhieuTra" Type="PhieuTra" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatMuonTaiLieu" Member="DatMuonTaiLieus">
    <Type Name="DatMuonTaiLieu">
      <Column Name="maDatMuon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maTaiLieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDatMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TaiLieu_DatMuonTaiLieu" Member="TaiLieu" ThisKey="maTaiLieu" OtherKey="maTaiLieu" Type="TaiLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocGia" Member="DocGias">
    <Type Name="DocGia">
      <Column Name="maDocGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenDocGia" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="cmnd" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="hide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DocGia_PhieuMuon" Member="PhieuMuons" ThisKey="maDocGia" OtherKey="maDocGia" Type="PhieuMuon" />
      <Association Name="DocGia_TheDocGia" Member="TheDocGia" ThisKey="maDocGia" OtherKey="maDocGia" Type="TheDocGia" Cardinality="One" />
      <Association Name="DocGia_XacNhanHuyThe" Member="XacNhanHuyThe" ThisKey="maDocGia" OtherKey="maDocGia" Type="XacNhanHuyThe" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiLieu" Member="LoaiTaiLieus">
    <Type Name="LoaiTaiLieu">
      <Column Name="maLoaiTaiLieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenLoai" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="LoaiTaiLieu_TaiLieu" Member="TaiLieus" ThisKey="maLoaiTaiLieu" OtherKey="maLoaiTaiLieu" Type="TaiLieu" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTinhTrangKhiTra" Member="LoaiTinhTrangKhiTras">
    <Type Name="LoaiTinhTrangKhiTra">
      <Column Name="maLoaiTinhTrang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenLoaiTinhTrang" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="LoaiTinhTrangKhiTra_ChiTietTinhTrangKhiTra" Member="ChiTietTinhTrangKhiTras" ThisKey="maLoaiTinhTrang" OtherKey="maLoaiTinhTrang" Type="ChiTietTinhTrangKhiTra" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuMuon" Member="PhieuMuons">
    <Type Name="PhieuMuon">
      <Column Name="maPhieuMuon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maDocGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maThuThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="PhieuMuon_ChiTietMuon" Member="ChiTietMuons" ThisKey="maPhieuMuon" OtherKey="maPhieuMuon" Type="ChiTietMuon" />
      <Association Name="PhieuMuon_PhieuTra" Member="PhieuTras" ThisKey="maPhieuMuon" OtherKey="maPhieumuon" Type="PhieuTra" />
      <Association Name="DocGia_PhieuMuon" Member="DocGia" ThisKey="maDocGia" OtherKey="maDocGia" Type="DocGia" IsForeignKey="true" />
      <Association Name="ThuThu_PhieuMuon" Member="ThuThu" ThisKey="maThuThu" OtherKey="maThuThu" Type="ThuThu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuTra" Member="PhieuTras">
    <Type Name="PhieuTra">
      <Column Name="maPhieuTra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maPhieumuon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maThuThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="PhieuTra_ChiTietTinhTrangKhiTra" Member="ChiTietTinhTrangKhiTras" ThisKey="maPhieuTra" OtherKey="maPhieuTra" Type="ChiTietTinhTrangKhiTra" />
      <Association Name="PhieuMuon_PhieuTra" Member="PhieuMuon" ThisKey="maPhieumuon" OtherKey="maPhieuMuon" Type="PhieuMuon" IsForeignKey="true" />
      <Association Name="ThuThu_PhieuTra" Member="ThuThu" ThisKey="maThuThu" OtherKey="maThuThu" Type="ThuThu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheDocGia" Member="TheDocGias">
    <Type Name="TheDocGia">
      <Column Name="maDocGia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayTaoThe" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DocGia_TheDocGia" Member="DocGia" ThisKey="maDocGia" OtherKey="maDocGia" Type="DocGia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiLieu" Member="TaiLieus">
    <Type Name="TaiLieu">
      <Column Name="maTaiLieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maLoaiTaiLieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenLoai" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="hide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TaiLieu_ChiTietMuon" Member="ChiTietMuons" ThisKey="maTaiLieu" OtherKey="maTaiLieu" Type="ChiTietMuon" />
      <Association Name="TaiLieu_DatMuonTaiLieu" Member="DatMuonTaiLieus" ThisKey="maTaiLieu" OtherKey="maTaiLieu" Type="DatMuonTaiLieu" />
      <Association Name="LoaiTaiLieu_TaiLieu" Member="LoaiTaiLieu" ThisKey="maLoaiTaiLieu" OtherKey="maLoaiTaiLieu" Type="LoaiTaiLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuThu" Member="ThuThus">
    <Type Name="ThuThu">
      <Column Name="maThuThu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenThuThu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="taiKhoan" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="matKhau" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="hide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ThuThu_PhieuMuon" Member="PhieuMuons" ThisKey="maThuThu" OtherKey="maThuThu" Type="PhieuMuon" />
      <Association Name="ThuThu_PhieuTra" Member="PhieuTras" ThisKey="maThuThu" OtherKey="maThuThu" Type="PhieuTra" />
    </Type>
  </Table>
  <Table Name="dbo.XacNhanHuyThe" Member="XacNhanHuyThes">
    <Type Name="XacNhanHuyThe">
      <Column Name="maDocGia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayMoLai" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DocGia_XacNhanHuyThe" Member="DocGia" ThisKey="maDocGia" OtherKey="maDocGia" Type="DocGia" IsForeignKey="true" />
    </Type>
  </Table>
</Database>